############## https://github.com/joeynmt/joeynmt/pull/216
#  Install the latest JoeyNMT:
#   $ git clone https://github.com/joeynmt/joeynmt.git
#   $ cd joeynmt
#   $ python -m pip install -e .
#
#  Prepare data: call `build_vocab.py` script from the project root path
#  This will generate sp.model and sp.vocab in /path/to/joeynmt/test/data/iwslt14/.
#   $ python scripts/build_vocab.py configs/iwslt14_deen_sp.yaml --joint
#
#  Train and test:
#   $ python -m joeynmt train configs/iwslt14_deen_bpe.yaml
#
#  Note that the data splits and preprocessing here are different from
#  the data splits created by scripts/get_iwslt14_sp.sh
#
name: "iwslt14_deen_sp"
joeynmt_version: "2.3.0"
task: "MT"
model_dir: "models/iwslt14_deen_sp"
use_cuda: True
fp16: True
random_seed: 42
num_workers: 0

data:
    train: "may-ohta/iwslt14"    # this downloads data from https://wit3.fbk.eu/2014-01
    dev: "may-ohta/iwslt14"      # ['TED.dev2010', 'TEDX.dev2012']
    test: "may-ohta/iwslt14"     # ['TED.tst2010', 'TED.tst2011', 'TED.tst2012']
    dataset_type: "huggingface"
    dataset_cfg:
        name: "de-en"
        trust_remote_code: True  # cf. https://huggingface.co/datasets/may-ohta/iwslt14
    src:
        lang: "de"
        max_length: 512
        lowercase: True
        normalize: False
        level: "bpe"
        voc_limit: 32000
        voc_min_freq: 1
        voc_file: "test/data/iwslt14/sp.vocab"
        tokenizer_type: "sentencepiece"
        tokenizer_cfg:
            model_file: "test/data/iwslt14/sp.model"
            model_type: "unigram"
            character_coverage: 1.0
            alpha: 0.1
            pretokenizer: "moses"
    trg:
        lang: "en"
        max_length: 512
        lowercase: True
        normalize: False
        level: "bpe"
        voc_limit: 32000
        voc_min_freq: 1
        voc_file: "test/data/iwslt14/sp.vocab"
        tokenizer_type: "sentencepiece"
        tokenizer_cfg:
            model_file: "test/data/iwslt14/sp.model"
            model_type: "unigram"
            character_coverage: 1.0
            alpha: 0.1
            pretokenizer: "moses"
    special_symbols:
        unk_token: "<unk>"
        unk_id: 0
        pad_token: "<pad>"
        pad_id: 1
        bos_token: "<s>"
        bos_id: 2
        eos_token: "</s>"
        eos_id: 3

testing:
    load_model: "models/iwslt14_deen_sp/best.ckpt"
    n_best: 1
    beam_size: 5
    beam_alpha: 1.0
    batch_size: 1024
    batch_type: "token"
    max_output_length: 100
    eval_metrics: ["bleu"]
    sacrebleu_cfg:
        tokenize: "13a"
        lowercase: True

training:
    #load_model: "models/iwslt14_deen_sp/latest.ckpt"
    #reset_best_ckpt: True
    #reset_scheduler: True
    #reset_optimizer: True
    #reset_iter_state: True
    optimizer: "adamw"
    normalization: "tokens"
    adam_betas: [0.9, 0.999]
    scheduling: "warmupinversesquareroot"
    learning_rate_warmup: 4000
    learning_rate: 0.0002
    learning_rate_min: 0.00000001
    weight_decay: 0.0
    label_smoothing: 0.1
    loss: "crossentropy"
    batch_size: 8192
    batch_type: "token"
    batch_multiplier: 4
    early_stopping_metric: "bleu"
    epochs: 100
    validation_freq: 1000
    logging_freq: 100
    overwrite: False
    shuffle: True
    print_valid_sents: [0, 1, 2, 3]
    keep_best_ckpts: 5

model:
    initializer: "xavier_uniform"
    bias_initializer: "zeros"
    init_gain: 1.0
    embed_initializer: "xavier_uniform"
    embed_init_gain: 1.0
    tied_embeddings: True
    tied_softmax: True
    encoder:
        type: "transformer"
        num_layers: 6
        num_heads: 8
        embeddings:
            embedding_dim: 512
            scale: True
            dropout: 0.
        # typically ff_size = 4 x hidden_size
        hidden_size: 512
        ff_size: 2048
        dropout: 0.1
        layer_norm: "pre"
        activation: "relu"
    decoder:
        type: "transformer"
        num_layers: 6
        num_heads: 8
        embeddings:
            embedding_dim: 512
            scale: True
            dropout: 0.
        # typically ff_size = 4 x hidden_size
        hidden_size: 512
        ff_size: 2048
        dropout: 0.1
        layer_norm: "pre"
        activation: "relu"
