############## https://github.com/joeynmt/joeynmt/pull/216
#  Install the latest JoeyNMT:
#   $ git clone https://github.com/joeynmt/joeynmt.git
#   $ cd joeynmt
#   $ python -m pip install -e .
#
#  Prepare data:
#   $ cd /path/to/joeynmt/scripts # Call the bash script from /path/to/joeynmt/scripts dir.
#   $ bash get_iwslt14_bpe.sh     # This will create /path/to/joeynmt/test/data/iwslt14/{train | valid | test}.{en | de}
#                                 # Make sure that /path/to/joeynmt/test/data/iwslt14/bpe.32000 exists, too.
#                                 # No need to call `build_vocab.py` script!
#   $ cd ..                       # now back to /path/to/joeynmt/
#
#  Train: comment out the `voc_file` lines in the data section -> vocab files will be created in the training process 
#   $ python -m joeynmt train configs/iwslt14_deen_bpe.yaml --skip-test
#
#  Test: uncomment the `vocab_file` lines below -> make sure that src_vocab.txt and trg_vocab.txt exist in model_dir
#   $ python -m joeynmt test configs/iwslt14_deen_bpe.yaml
#
name: "transformer_iwslt14_deen_bpe"
joeynmt_version: "2.3.0"
task: "MT"
model_dir: "models/transformer_iwslt14_deen_bpe"
use_cuda: True
fp16: False
random_seed: 42
num_workers: 0

data:
    train: "test/data/iwslt14/train"
    dev: "test/data/iwslt14/valid"
    test: "test/data/iwslt14/test"
    dataset_type: "plain"
    src:
        lang: "de"
        max_length: 62
        lowercase: True
        normalize: False
        level: "bpe"
        voc_min_freq: 1
        #voc_file: "models/transformer_iwslt14_deen_bpe/src_vocab.txt"
        tokenizer_type: "subword-nmt"
        tokenizer_cfg:
            num_merges: 32000
            codes: "test/data/iwslt14/bpe.32000"
            pretokenizer: "none"
    trg:
        lang: "en"
        max_length: 62
        lowercase: True
        normalize: False
        level: "bpe"
        voc_min_freq: 1
        #voc_file: "models/transformer_iwslt14_deen_bpe/trg_vocab.txt"
        tokenizer_type: "subword-nmt"
        tokenizer_cfg:
            num_merges: 32000
            codes: "test/data/iwslt14/bpe.32000"
            pretokenizer: "none"
    special_symbols:
        unk_token: "<unk>"
        unk_id: 0
        pad_token: "<pad>"
        pad_id: 1
        bos_token: "<s>"
        bos_id: 2
        eos_token: "</s>"
        eos_id: 3

testing:
    load_model: "models/transformer_iwslt14_deen_bpe/best.ckpt"
    n_best: 1
    beam_size: 5
    beam_alpha: 1.0
    batch_size: 1024
    batch_type: "token"
    max_output_length: 100
    eval_metrics: ["bleu"]
    return_prob: "none"
    return_attention: False
    sacrebleu_cfg:
        tokenize: "13a"
        lowercase: True

training:
    #load_model: "models/transformer_iwslt14_deen_bpe/latest.ckpt"
    optimizer: "adamw"
    normalization: "tokens"
    adam_betas: [0.9, 0.999]
    scheduling: "plateau"
    patience: 5
    decrease_factor: 0.7
    loss: "crossentropy"
    learning_rate: 0.0003
    learning_rate_min: 0.00000001
    weight_decay: 0.0
    label_smoothing: 0.1
    batch_size: 4096
    batch_type: "token"
    early_stopping_metric: "bleu"
    epochs: 100
    validation_freq: 1000
    logging_freq: 100
    overwrite: False
    shuffle: True
    print_valid_sents: [0, 1, 2, 3, 4]
    keep_best_ckpts: 5

model:
    initializer: "xavier_uniform"
    embed_initializer: "xavier_uniform"
    embed_init_gain: 1.0
    init_gain: 1.0
    bias_initializer: "zeros"
    tied_embeddings: True
    tied_softmax: True
    encoder:
        type: "transformer"
        num_layers: 6
        num_heads: 4
        embeddings:
            embedding_dim: 256
            scale: True
            dropout: 0.
        # typically ff_size = 4 x hidden_size
        hidden_size: 256
        ff_size: 1024
        dropout: 0.3
        layer_norm: "pre"
        activation: "relu"
    decoder:
        type: "transformer"
        num_layers: 6
        num_heads: 4
        embeddings:
            embedding_dim: 256
            scale: True
            dropout: 0.
        # typically ff_size = 4 x hidden_size
        hidden_size: 256
        ff_size: 1024
        dropout: 0.3
        layer_norm: "pre"
        activation: "relu"
